apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: core
build:
  local: {}
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: model-server
      jib:
        project: model-server
    - image: mps-git-import-base
      context: mps-base-image
    - image: mps-git-import
      jib:
        project: mps-git-import-cli
        fromImage: mps-git-import-base
      requires:
        - image: mps-git-import-base
