package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import java.util.function.Consumer;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;

public class _Adapters {
  public static class _return_P1_E0_to_Consumer_adapter<P1> implements Consumer<P1> {
    private _FunctionTypes._return_P1_E0<? extends Object, ? super P1> adapted;
    public _return_P1_E0_to_Consumer_adapter(_FunctionTypes._return_P1_E0<? extends Object, ? super P1> adapted) {
      this.adapted = adapted;
    }
    public void accept(P1 param1) {
      this.adapted.invoke(param1);
    }
  }
}
