package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import java.util.Set;
import com.intellij.openapi.util.Pair;
import jetbrains.mps.workbench.ActionPlace;
import org.jetbrains.mps.util.Condition;
import jetbrains.mps.workbench.action.BaseAction;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.HashSet;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;
import com.intellij.openapi.actionSystem.AnActionEvent;
import org.modelix.model.mpsplugin.CloudRepository;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.modelix.model.mpsplugin.ModelServerConnections;
import java.util.function.Consumer;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.Nullable;

public class CloudActionsForPhysicalProjectsCloudActions_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.modelix.model.mpsplugin.plugin.CloudActionsForPhysicalProjectsCloudActions_ActionGroup";
  private final Set<Pair<ActionPlace, Condition<BaseAction>>> myPlaces = SetSequence.fromSet(new HashSet<Pair<ActionPlace, Condition<BaseAction>>>());

  public CloudActionsForPhysicalProjectsCloudActions_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("Cloud Actions", ID, plugin);
    setIsInternal(false);
    setPopup(true);
  }
  public void doUpdate(AnActionEvent event) {
    removeAll();
    for (final CloudRepository treeInRepository : Sequence.fromIterable(ModelServerConnections.getInstance().getConnectedTreesInRepositories())) {
      treeInRepository.processProjects(new Consumer<SNode>() {
        public void accept(SNode pr) {
          CloudActionsForPhysicalProjectsCloudActions_ActionGroup.this.addParameterizedAction(new CopyAndSyncPhysicalProjectOnCloud_Action(treeInRepository, pr), treeInRepository, pr);
        }
      });
      CloudActionsForPhysicalProjectsCloudActions_ActionGroup.this.addParameterizedAction(new CopyAndSyncPhysicalProjectOnCloud_Action(treeInRepository, null), treeInRepository, null);
    }
    for (Pair<ActionPlace, Condition<BaseAction>> p : this.myPlaces) {
      this.addPlace(p.first, p.second);
    }
  }
  public void addPlace(ActionPlace place, @Nullable Condition<BaseAction> cond) {
    SetSequence.fromSet(this.myPlaces).addElement(new Pair<ActionPlace, Condition<BaseAction>>(place, cond));
  }
  public boolean isStrict() {
    return false;
  }
}
