package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.workbench.action.ActionAccess;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import javax.swing.tree.TreeNode;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.mpsplugin.history.RepositoryTreeNode;
import org.modelix.model.client.ActiveBranch;
import org.modelix.model.api.IBranch;
import kotlin.jvm.functions.Function0;
import org.modelix.model.api.ITree;
import org.modelix.model.lazy.ITreeWrapperKt;
import org.modelix.model.lazy.CLTree;
import com.intellij.openapi.ui.Messages;

public class GetCloudRepositorySize_Action extends BaseAction {
  private static final Icon ICON = null;

  public GetCloudRepositorySize_Action() {
    super("Get Number of Nodes", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setActionAccess(ActionAccess.UNDO_PROJECT);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      Project p = event.getData(CommonDataKeys.PROJECT);
      if (p == null) {
        return false;
      }
    }
    {
      TreeNode p = event.getData(MPSCommonDataKeys.TREE_NODE);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    RepositoryTreeNode treeNode = (RepositoryTreeNode) event.getData(MPSCommonDataKeys.TREE_NODE);
    ActiveBranch activeBranch = treeNode.getModelServer().getActiveBranch(treeNode.getRepositoryId());
    final IBranch branch = activeBranch.getBranch();
    long size = branch.computeRead(new Function0<Long>() {
      public Long invoke() {
        ITree tree = ITreeWrapperKt.unwrap(branch.getTransaction().getTree());
        if (tree instanceof CLTree) {
          return ((CLTree) tree).getSize();
        }
        return 0L;
      }
    });
    Messages.showInfoMessage(event.getData(CommonDataKeys.PROJECT), "Size is " + size, "Size of Repository");
  }
}
