package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import javax.swing.tree.TreeNode;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.mpsplugin.history.CloudBranchTreeNode;
import org.modelix.model.mpsplugin.history.RepositoryTreeNode;
import org.modelix.model.api.IBranch;
import org.modelix.model.area.PArea;
import kotlin.jvm.functions.Function0;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.modelix.model.lazy.RepositoryId;
import org.modelix.model.mpsplugin.ModelServerConnection;
import org.modelix.model.client.IModelClient;
import org.modelix.model.mpsplugin.SharedExecutors;
import org.modelix.model.lazy.CLVersion;
import javax.swing.SwingUtilities;
import jetbrains.mps.plugins.projectplugins.ProjectPluginManager;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class LoadHistoryForBranch_Action extends BaseAction {
  private static final Icon ICON = null;

  public LoadHistoryForBranch_Action() {
    super("Show History", "", ICON);
    this.setIsAlwaysVisible(false);
    this.setExecuteOutsideCommand(true);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      Project p = event.getData(CommonDataKeys.PROJECT);
      if (p == null) {
        return false;
      }
    }
    {
      TreeNode p = event.getData(MPSCommonDataKeys.TREE_NODE);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    final CloudBranchTreeNode branchTNode = (CloudBranchTreeNode) event.getData(MPSCommonDataKeys.TREE_NODE);
    RepositoryTreeNode treeTNode = branchTNode.getAncestor(RepositoryTreeNode.class);
    IBranch infoBranch = treeTNode.getModelServer().getInfoBranch();
    String branchName = new PArea(infoBranch).executeRead(new Function0<String>() {
      public String invoke() {
        return SPropertyOperations.getString(branchTNode.getBranchInfo(), PROPS.name$MnvL);
      }
    });
    final RepositoryId repositoryId = treeTNode.getRepositoryId();
    final String branchKey = repositoryId.getBranchKey(branchName);
    final ModelServerConnection modelServer = treeTNode.getModelServer();
    final IModelClient client = modelServer.getClient();
    SharedExecutors.FIXED.execute(new Runnable() {
      public void run() {
        String versionHash = client.get(branchKey);
        final CLVersion version = CLVersion.Companion.loadFromHash(versionHash, client.getStoreCache());
        SwingUtilities.invokeLater(new Runnable() {
          public void run() {
            event.getData(CommonDataKeys.PROJECT).getComponent(ProjectPluginManager.class).getTool(CloudHistoryTool_Tool.class).load(modelServer, repositoryId, new _FunctionTypes._return_P0_E0<CLVersion>() {
              public CLVersion invoke() {
                return version;
              }
            });
          }
        });
      }
    });
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
