package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.modelix.model.mpsadapters.mps.BootstrapConceptMappings;
import org.modelix.model.metameta.MetaMetaLanguage;
import org.apache.log4j.Level;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MetaMetaModelMappings {
  private static final Logger LOG = LogManager.getLogger(MetaMetaModelMappings.class);
  public static void register() {
    try {
      BootstrapConceptMappings.INSTANCE.register(MetaMetaLanguage.INSTANCE.getConcept_Language(), CONCEPTS.Language$L1);
      BootstrapConceptMappings.INSTANCE.register(MetaMetaLanguage.INSTANCE.getConcept_Concept(), CONCEPTS.Concept$Lw);
      BootstrapConceptMappings.INSTANCE.register(MetaMetaLanguage.INSTANCE.getConcept_Property(), CONCEPTS.Property$LZ);
      BootstrapConceptMappings.INSTANCE.register(MetaMetaLanguage.INSTANCE.getConcept_ChildLink(), CONCEPTS.ContainmentLink$X8);
      BootstrapConceptMappings.INSTANCE.register(MetaMetaLanguage.INSTANCE.getConcept_ReferenceLink(), CONCEPTS.ReferenceLink$WD);
    } catch (Exception ex) {
      if (LOG.isEnabledFor(Level.ERROR)) {
        LOG.error("", ex);
      }
    }
  }
  public static void unregister() {
    try {
      BootstrapConceptMappings.INSTANCE.unregister(MetaMetaLanguage.INSTANCE.getConcept_Language(), CONCEPTS.Language$L1);
      BootstrapConceptMappings.INSTANCE.unregister(MetaMetaLanguage.INSTANCE.getConcept_Concept(), CONCEPTS.Concept$Lw);
      BootstrapConceptMappings.INSTANCE.unregister(MetaMetaLanguage.INSTANCE.getConcept_Property(), CONCEPTS.Property$LZ);
      BootstrapConceptMappings.INSTANCE.unregister(MetaMetaLanguage.INSTANCE.getConcept_ChildLink(), CONCEPTS.ContainmentLink$X8);
      BootstrapConceptMappings.INSTANCE.unregister(MetaMetaLanguage.INSTANCE.getConcept_ReferenceLink(), CONCEPTS.ReferenceLink$WD);
    } catch (Exception ex) {
      if (LOG.isEnabledFor(Level.ERROR)) {
        LOG.error("", ex);
      }
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Language$L1 = MetaAdapterFactory.getConcept(0xbffdf1230d7b471bL, 0xa52bfa3d3a024664L, 0x100c617ef3bce7efL, "org.modelix.model.metametamodel.structure.Language");
    /*package*/ static final SConcept Concept$Lw = MetaAdapterFactory.getConcept(0xbffdf1230d7b471bL, 0xa52bfa3d3a024664L, 0x100c617ef3bce7f0L, "org.modelix.model.metametamodel.structure.Concept");
    /*package*/ static final SConcept Property$LZ = MetaAdapterFactory.getConcept(0xbffdf1230d7b471bL, 0xa52bfa3d3a024664L, 0x100c617ef3bce7f1L, "org.modelix.model.metametamodel.structure.Property");
    /*package*/ static final SConcept ContainmentLink$X8 = MetaAdapterFactory.getConcept(0xbffdf1230d7b471bL, 0xa52bfa3d3a024664L, 0x100c617ef3bce7f3L, "org.modelix.model.metametamodel.structure.ContainmentLink");
    /*package*/ static final SConcept ReferenceLink$WD = MetaAdapterFactory.getConcept(0xbffdf1230d7b471bL, 0xa52bfa3d3a024664L, 0x100c617ef3bce7f2L, "org.modelix.model.metametamodel.structure.ReferenceLink");
  }
}
