package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class ModelServerGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.modelix.model.mpsplugin.plugin.ModelServerGroup_ActionGroup";

  public ModelServerGroup_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("ModelServerGroup", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    ModelServerGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.RemoveModelServer_Action");
    ModelServerGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.AddRepository_Action");
    ModelServerGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.ShowAuthenticationInfo_Action");
    ModelServerGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.Reconnect_Action");
  }
}
