= Gradle Helper for the Model API Generator
:navtitle: `metamodel.gradle`


:tip-caption: 🔗 Quick Links
[TIP]
--
https://artifacts.itemis.cloud/#browse/browse:maven-mps:org%2Fmodelix%2Fmetamodel-gradle%2Fmaven-metadata.xml[Nexus^] | https://github.com/modelix/modelix.core[Repository^] | https://github.com/modelix/modelix.core/blob/main/metamodel-gradle/build.gradle.kts[Buildfile^]
--


The `org.modelix.metamodel.gradle` is a Gradle plugin that wraps the functionality of the xref:core:reference/component-metamodel-generator.adoc[meta-model generator].
It provides an additional Gradle task which will apply a 2-saged process:

. MPS meta-model export to YAML
+
In the first step the https://github.com/JetBrains/MPS-extensions[MPS Extensions^] are used to export the MPS structure aspect (i.e. the meta-model) into a YAML file.
In case your meta-model comes from another source this is an external entry point: As long as you can export your meta-model to YAML, you can use the xref:core:reference/component-metamodel-generator.adoc[model API generator]

. YAML to model API generation
+
In the second step, the previously generated YAML file containing the meta-model is generated using the kotlin generator in xref:core:reference/component-metamodel-generator.adoc[]

