package org.modelix.model.mpsplugin;

/*Generated by MPS */

import com.intellij.notification.Notifications;
import com.intellij.notification.Notification;
import com.intellij.notification.NotificationType;
import jetbrains.mps.project.MPSProject;
import jetbrains.mps.ide.project.ProjectHelper;

public class ModelixNotifications {
  private static final String GROUP_ID = "modelix";
  public static void notifyWarning(String title, String message) {
    Notifications.Bus.notify(new Notification(GROUP_ID, title, message, NotificationType.WARNING));
  }

  public static void notifyError(String title, String message) {
    Notifications.Bus.notify(new Notification(GROUP_ID, title, message, NotificationType.ERROR));
  }
  public static void notifyError(String title, String message, MPSProject mpsProject) {
    Notifications.Bus.notify(new Notification(GROUP_ID, title, message, NotificationType.ERROR), ProjectHelper.toIdeaProject(mpsProject));
  }
}
