package org.modelix.model.mpsplugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class ModuleUtils {
  public ModuleUtils() {
  }
  public static void printModulesNames(final SModule _this, String comment) {
    StringBuilder sb = new StringBuilder();
    boolean empty = true;
    for (SModel m : ListSequence.fromList(SModuleUtils.getModelsWithoutDescriptor(_this))) {
      if (empty) {
        empty = false;
      } else {
        sb.append(", ");
      }
      sb.append(m.getModelName());
    }
  }
}
