package org.modelix.model.mpsplugin;

/*Generated by MPS */

import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.project.*;
import jetbrains.mps.smodel.ModuleDependencyVersions;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.module.SModule;

import java.io.File;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.openapi.vfs.LocalFileSystem;
import java.io.IOException;
import java.util.List;

import jetbrains.mps.vfs.IFile;
import de.slisson.mps.reflection.runtime.ReflectionUtil;
import jetbrains.mps.ide.newSolutionDialog.NewModuleUtil;
import jetbrains.mps.project.structure.modules.SolutionDescriptor;
import jetbrains.mps.smodel.GeneralModuleFactory;

public class MPSProjectUtils {
  public MPSProjectUtils() {
  }
  public static SModule createModule(final MPSProject _this, String nameSpace, ModuleId moduleId, Object requestor) {
    if (nameSpace == null) {
      throw new IllegalArgumentException("nameSpace should not be null");
    }

    // A module may already exist in the global repository, but is just not part of the project yet.
    SModule existingModule = _this.getRepository().getModule(moduleId);
    if (existingModule != null) {
      _this.addModule(existingModule);
      return existingModule;
    }

    File moduleFolder = new File(_this.getProjectFile(), nameSpace);
    VirtualFile moduleFolder_ = LocalFileSystem.getInstance().findFileByIoFile(moduleFolder);
    if (moduleFolder_ != null && moduleFolder_.exists()) {
      try {
        moduleFolder_.delete(requestor);
      } catch (IOException e) {
        throw new RuntimeException("Failed to delete " + moduleFolder_, e);
      }
    }

    IFile descriptorFile = (IFile) ReflectionUtil.callStaticMethod(NewModuleUtil.class, "getModuleFile", new Class[]{String.class, String.class, String.class}, new Object[]{nameSpace, moduleFolder.getAbsolutePath(), MPSExtentions.DOT_SOLUTION});
    if (descriptorFile == null) {
      throw new IllegalStateException("descriptor file should not be null");
    }
    SolutionDescriptor descriptor = (SolutionDescriptor) ReflectionUtil.callStaticMethod(NewModuleUtil.class, "createNewSolutionDescriptor", new Class[]{String.class, IFile.class}, new Object[]{nameSpace, descriptorFile});

    descriptor.setId(moduleId);
    Solution module = (Solution) new GeneralModuleFactory().instantiate(descriptor, descriptorFile);
    _this.addModule(module);
    new ModuleDependencyVersions(LanguageRegistry.getInstance(_this.getRepository()), _this.getRepository()).update(module);
    module.save();
    return module;
  }
}
