package org.modelix.metamodel

/**
 * Superinterface for enums generated by model-api-gen
 */
interface IPropertyValueEnum {

    /**
     * Name of the enum literal.
     */
    val name: String

    /**
     * Textual representation of the enum value.
     * Null, if undefined.
     */
    val presentation: String?
}
