package org.modelix.model.mpsplugin;

/*Generated by MPS */

import org.modelix.model.api.INode;
import org.modelix.model.mpsplugin.history.CloudNodeTreeNode;
import org.modelix.model.api.PNodeAdapter;
import org.modelix.model.area.PArea;
import kotlin.jvm.functions.Function0;
import org.modelix.model.mpsadapters.mps.SConceptAdapter;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class CloudNodeTreeNodeCreationMethods {
  public CloudNodeTreeNodeCreationMethods() {
  }
  public static INode createProject(final CloudNodeTreeNode _this, String moduleName) {
    // TODO check this represent a repository/a tree root
    return PNodeAdapterCreationMethods.createProject(((PNodeAdapter) _this.getNode()), moduleName);
  }
  public static INode createModule(final CloudNodeTreeNode _this, String moduleName) {
    // TODO check this represent a repository/a tree root
    return PNodeAdapterCreationMethods.createModuleInRepository(((PNodeAdapter) _this.getNode()), moduleName);
  }
  public static INode createModel(final CloudNodeTreeNode _this, final String modelName) {
    // TODO check this represent a module
    return new PArea(_this.getBranch()).executeWrite(new Function0<INode>() {
      public INode invoke() {
        INode newModel = _this.getNode().addNewChild(LINKS.models$h3QT.getName(), -1, SConceptAdapter.wrap(CONCEPTS.Model$2P));
        newModel.setPropertyValue(PROPS.name$MnvL.getName(), modelName);
        return newModel;
      }
    });
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink models$h3QT = MetaAdapterFactory.getContainmentLink(0xa7577d1d4e5431dL, 0x98b1fae38f9aee80L, 0x69652614fd1c50fL, 0x69652614fd1c512L, "models");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Model$2P = MetaAdapterFactory.getConcept(0xa7577d1d4e5431dL, 0x98b1fae38f9aee80L, 0x69652614fd1c50cL, "org.modelix.model.repositoryconcepts.structure.Model");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
