package org.modelix.model.mpsplugin;

/*Generated by MPS */

import org.modelix.model.api.IBranch;
import org.modelix.model.client.IIndirectBranch;
import org.modelix.model.lazy.RepositoryId;

public interface ICloudRepository {
  IBranch getBranch();
  IIndirectBranch getActiveBranch();
  String completeId();
  RepositoryId getRepositoryId();
}
