package org.modelix.model.mpsplugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.module.SRepository;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.project.Project;
import jetbrains.mps.project.SModuleOperations;

public class ModelAccess {
  public ModelAccess() {
  }
  public static void runInWriteActionIfNeeded(final SModel _this, final Runnable runnable) {
    SRepository repo = null;
    SModule module = _this.getModule();
    if (module != null) {
      Project project = SModuleOperations.getProjectForModule(module);
      if (project != null) {
        repo = project.getRepository();
      }
    }
    if (repo == null) {
      runnable.run();
    } else {
      repo.getModelAccess().runWriteAction(new Runnable() {
        public void run() {
          runnable.run();
        }
      });
    }
  }
}
