package org.modelix.model.mpsplugin;

/*Generated by MPS */

import org.modelix.model.client.IIndirectBranch;
import org.modelix.model.api.IBranch;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.IBranchListener;

public class NonIndirectBranch implements IIndirectBranch {
  private IBranch branch;

  public NonIndirectBranch(IBranch branch) {
    this.branch = branch;
  }

  @Override
  public void addListener(@NotNull IBranchListener listener) {
    branch.addListener(listener);
  }

  @NotNull
  @Override
  public IBranch getBranch() {
    return branch;
  }

  @Override
  public void removeListener(@NotNull IBranchListener listener) {
    branch.removeListener(listener);
  }
}
