package org.modelix.model.mpsplugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import org.modelix.model.api.INode;

/**
 * This represents just a pair of associated models: one physical and one on the cloud.
 */
public class PhysicalToCloudModelMapping {
  private SModel physicalModel;
  private INode cloudModel;

  public SModel getPhysicalModel() {
    return physicalModel;
  }

  public INode getCloudModel() {
    return cloudModel;
  }

  public PhysicalToCloudModelMapping(SModel physicalModel, INode cloudModel) {
    this.physicalModel = physicalModel;
    this.cloudModel = cloudModel;
  }
}
