package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class CloudBindingGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.modelix.model.mpsplugin.plugin.CloudBindingGroup_ActionGroup";

  public CloudBindingGroup_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("CloudBindingGroup", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    CloudBindingGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.Unbind_Action");
  }
}
