package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindow;
import com.intellij.openapi.wm.ToolWindowFactory;
import com.intellij.ui.content.ContentFactory;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.mpsplugin.history.CloudView;

import javax.swing.Icon;


public class CloudTool_Tool implements ToolWindowFactory {
  private static final Icon ICON = IconContainer.ICON_a0;
  private CloudView component;

  @Override
  public void createToolWindowContent(@NotNull Project project, @NotNull ToolWindow toolWindow) {
    component = new CloudView();
    toolWindow.getContentManager().addContent(ContentFactory.SERVICE.getInstance().createContent(component, "Modelix Server", false));
  }
}
