package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconLoadingUtil;

public class IconContainer {
  public static Icon ICON_a0 = IconLoadingUtil.loadIcon("TextIcon_1.png", IconContainer.class);
  public static Icon ICON_a0_0 = IconLoadingUtil.loadIcon("TextIcon_13262.png", IconContainer.class);
}
