package org.modelix.model.mpsplugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class RepositoryGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.modelix.model.mpsplugin.plugin.RepositoryGroup_ActionGroup";

  public RepositoryGroup_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("RepositoryGroup", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    RepositoryGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.LoadHistoryForRepository_Action");
    RepositoryGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.RemoveRepository_Action");
    RepositoryGroup_ActionGroup.this.addAction("org.modelix.model.mpsplugin.plugin.GetCloudRepositorySize_Action");
  }
}
