package org.modelix.common;

/*Generated by MPS */

import de.q60.mps.incremental.util.ContextValue;

public class AuthorOverride {
  public static ContextValue<String> AUTHOR = new ContextValue<String>();
  private static String instanceOwner = null;

  public static void setInstanceOwner(String owner) {
    instanceOwner = owner;
  }

  public static String apply(String author) {
    String override = AUTHOR.getValue();
    if ((override != null && override.length() > 0)) {
      return override;
    }
    if ((author == null || author.length() == 0) && (instanceOwner != null && instanceOwner.length() > 0)) {
      return instanceOwner;
    }
    return author;
  }
}
