name: Code linting

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: node_modules
          key: release-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  openapi-linting:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: stoplightio/spectral-action@2ad0b9302e32a77c1caccf474a9b2191a8060d83 # v0.8.11
        with:
          file_glob: 'model-server-openapi/specifications/model-server-*.yaml'
          spectral_ruleset: .spectral.yaml
        continue-on-error: true

  openapi-breaking-changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # We need the history to find the common ancestor of the PR and the target branch from which we fetch the
          # baseline OpenAPI specifications to compare against.
          fetch-depth: 0
      - name: Fetch baseline OpenAPI specifications
        run: |
          mergeBase="$(git merge-base --fork-point "origin/${{ github.base_ref }}")"
          echo "mergeBase: $mergeBase"
          git restore -s "$mergeBase" -W -- model-server-openapi/specifications
          cp -R model-server-openapi/specifications model-server-openapi/specifications-before
          git checkout model-server-openapi/specifications
      - name: Run oasdiff
        id: breaking
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: 'model-server-openapi/specifications-before/*.yaml'
          revision: 'model-server-openapi/specifications/*.yaml'
          composed: true
