name: Code linting

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: release-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  openapi-breaking-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          # We need the history to find the common ancestor of the PR and the target branch from which we fetch the
          # baseline OpenAPI specifications to compare against.
          fetch-depth: 0
      - name: Fetch baseline OpenAPI specifications
        run: |
          mergeBase="$(git merge-base --fork-point "origin/${{ github.base_ref }}")"
          echo "mergeBase: $mergeBase"
          git restore -s "$mergeBase" -W -- model-server-openapi/specifications
          cp -R model-server-openapi/specifications model-server-openapi/specifications-before
          git checkout model-server-openapi/specifications
      - name: Run oasdiff
        id: breaking
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: 'model-server-openapi/specifications-before/*.yaml'
          revision: 'model-server-openapi/specifications/*.yaml'
          composed: true
