name: Code linting

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: node_modules
          key: release-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

#  openapi-linting:
#    runs-on: ubuntu-24.04
#    steps:
#      - name: Clone repo
#        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
#      - uses: stoplightio/spectral-action@6416fd018ae38e60136775066eb3e98172143141 # v0.8.13
#        with:
#          file_glob: 'model-server-openapi/specifications/model-server-*.yaml'
#          spectral_ruleset: .spectral.yaml
#        continue-on-error: true

  openapi-breaking-changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: Clone repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          # We need the history to find the common ancestor of the PR and the target branch from which we fetch the
          # baseline OpenAPI specifications to compare against.
          fetch-depth: 0
      - name: Fetch baseline OpenAPI specifications
        run: |
          mergeBase="$(git merge-base --fork-point "origin/${{ github.base_ref }}")"
          echo "mergeBase: $mergeBase"
          git restore -s "$mergeBase" -W -- model-server-openapi/specifications
          cp -R model-server-openapi/specifications model-server-openapi/specifications-before
          git checkout model-server-openapi/specifications
      - name: Run oasdiff
        id: breaking
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: 'model-server-openapi/specifications-before/*.yaml'
          revision: 'model-server-openapi/specifications/*.yaml'
          composed: true
